In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x_train = np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35]])
y_train = np.array([460,232,178])
print(x_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]


In [6]:
def predict(x,w,b):
    return (np.dot(x,w)+b)

In [8]:
def compute_gradient(x,y,w,b):
    m,n = x.shape
    dj_dw = np.zeros(n)
    dj_db = 0.0
    for i in range(m):
        err = (np.dot(x[i],w)+b)-y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * x[i,j]
        dj_db = dj_db + err
    dj_dw = dj_dw /m
    dj_db = dj_db/m
    return dj_dw, dj_db

In [10]:
def gradient_decent(x,y,w_in, b_in, alpha, num_iter, compute_gradient):
    w = w_in
    b = b_in
    for i in range(num_iter):
        dj_dw, dj_db = compute_gradient(x,y,w,b)
        w = w - alpha * dj_dw
        b = b - alpha * dj_db
    return w,b
        

In [12]:
w = np.zeros_like(x_train[0])
b=0
alpha = 5.0e-7
iterations=1000
w,b = gradient_decent(x_train, y_train, w,b,alpha, iterations, compute_gradient)
print(f"Value of (w,b) is: (w: {w}, b:{b})")

Value of (w,b) is: (w: [ 0.20396569  0.00374919 -0.0112487  -0.0658614 ], b:-0.0022354075309325345)


In [14]:
predicted_price = predict(x_train,w,b)
print(predicted_price)

[426.18530497 286.16747201 171.46763087]


In [18]:
# plt.title("House Price Prediction multiple parametrs")
# plt.plot(x_train[0], predicted_price, c='b')
# plt.scatter(x_train[0], predicted_price, marker='x', c='r',label='Predicated prices')
# plt.scatter(x_train[0], y_train, c='b', marker='o', label="Givn Prices")
# plt.legend()
# plt.show()